### ISSUE TITLE
Can't find pretrained model

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/AIR-Act2Act.pytorch#1]
Prerequisites에 'We already provide a trained model in 'models/lstm/vector/model_0013.pth'.'라 명시되어 있는데, .gitignore에서 아래와 같이 코드가 입력되어 있어 .pth 파일이 업로드되지 않은 것 같습니다. gitignore 파일을 삭제하거나 Google Drive에 .pth 파일을 업로드해주시면 감사하겠습니다.

-.gitignore 내용
> Ignore everything in this directory
>*
> Except this file
>!.gitignore

**Comment by wrko** [comment]
Thanks for your comment.
I uploaded the pre-trained model in models/lstm/vector/.
