### ISSUE TITLE
Modules used in Act2Act.pytorch

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/AIR-Act2Act.pytorch#2]
AIR-Act2Act.pytorch의 파일을 실행하는 데에 아래와 같은 모듈이 추가적으로 필요합니다. GPU를 사용해야 해서 pip install pytorch 대신 GPU  버전 pytorch를 설치해야 합니다.

> pip install pandas sklearn  
> cuda 9.2 installation - https://developer.nvidia.com/cuda-92-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal  
> conda install pytorch=0.4.1 cuda92 -c pytorch

**Comment by wrko** [comment]
I have updated the README.md file.
Please check again if it is modified as intended.

**Comment by kjwoo31** [comment]
$ pip install simplejson tqdm matplotlib argparse
$ pip install pandas sklearn
$ conda install pytorch=0.4.1 cuda92 -c pytorch

을 아래와 같이 수정해주세요.

$ pip install simplejson tqdm matplotlib argparse pandas sklearn
$ conda install pytorch=0.4.1 cuda92 -c pytorch
cuda 9.2 installation - [here](https://developer.nvidia.com/cuda-92-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal)

감사합니다.

**Comment by wrko** [comment]
Done.
